"""add user context

Revision ID: 31ff27cf5b3e
Revises: a6ce141a3d8a
Create Date: 2025-12-15 19:41:35.353392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31ff27cf5b3e'
down_revision: Union[str, Sequence[str], None] = 'a6ce141a3d8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_context',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.Integer(), nullable=False),
    sa.Column('mode', sa.Enum('noSelect', 'relax', 'focus', 'exercise', 'social', name='modeenum'), nullable=False),
    sa.Column('place', sa.Text(), nullable=False),
    sa.Column('tool', sa.ARRAY(sa.Enum('noSelect', 'Phone', 'computer', 'ipad', 'textbook', 'notebook', name='toolenum')), nullable=False),
    sa.Column('created_at', sa.Text(), server_default=sa.text("'NOW()'::text"), nullable=True),
    sa.Column('updated_at', sa.Text(), server_default=sa.text("'NOW()'::text"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_context_id'), 'user_context', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_context_id'), table_name='user_context')
    op.drop_table('user_context')
    # ### end Alembic commands ###
