"""add user context

Revision ID: 58e48bb2b715
Revises: a6ce141a3d8a
Create Date: 2025-12-15 20:08:19.364066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '58e48bb2b715'
down_revision: Union[str, Sequence[str], None] = 'a6ce141a3d8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum types using raw SQL with IF NOT EXISTS
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE modeenum AS ENUM ('noSelect', 'relax', 'focus', 'exercise', 'social');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)
    
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE toolenum AS ENUM ('noSelect', 'Phone', 'computer', 'ipad', 'textbook', 'notebook');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)
    
    # Create table using raw SQL to avoid enum type recreation issues
    op.execute("""
        CREATE TABLE IF NOT EXISTS user_context (
            id SERIAL PRIMARY KEY,
            time INTEGER NOT NULL,
            mode modeenum NOT NULL,
            place TEXT NOT NULL,
            tool toolenum[] NOT NULL,
            created_at TEXT DEFAULT 'NOW()',
            updated_at TEXT DEFAULT 'NOW()'
        )
    """)
    
    # Create index if it doesn't exist
    op.execute("""
        CREATE INDEX IF NOT EXISTS ix_user_context_id ON user_context (id)
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_context_id'), table_name='user_context')
    op.drop_table('user_context')
    
    # Note: We don't drop the enum types here because they might be used by other tables
    # If you need to drop them, uncomment the following lines:
    # postgresql.ENUM(name='modeenum').drop(op.get_bind(), checkfirst=True)
    # postgresql.ENUM(name='toolenum').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
