"""update_tasks_table

Revision ID: a6ce141a3d8a
Revises: 096717a1c7e7
Create Date: 2025-12-15 16:53:07.733869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6ce141a3d8a'
down_revision: Union[str, Sequence[str], None] = '096717a1c7e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag_groups', sa.Column('is_single_select', sa.Boolean(), nullable=False))
    op.add_column('tag_groups', sa.Column('allow_add_tag', sa.Boolean(), nullable=False))
    op.add_column('tag_groups', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('tag_groups', 'is_system')
    op.add_column('tags', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'created_at')
    op.add_column('tag_groups', sa.Column('is_system', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('tag_groups', 'created_at')
    op.drop_column('tag_groups', 'allow_add_tag')
    op.drop_column('tag_groups', 'is_single_select')
    # ### end Alembic commands ###
