"""create records

Revision ID: d4b6d1b1b65e
Revises: 76cb7f09ee91
Create Date: 2025-12-11 07:17:46.172441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd4b6d1b1b65e'
down_revision: Union[str, Sequence[str], None] = '76cb7f09ee91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_records_occurred_at'), table_name='records')
    op.drop_index(op.f('ix_records_task_id'), table_name='records')
    op.drop_index(op.f('ix_records_user_id'), table_name='records')
    op.drop_table('records')
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_table('records',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('mode', postgresql.ENUM('noSelect', 'relax', 'focus', 'exercise', 'social', name='modeenum'), autoincrement=False, nullable=True),
    sa.Column('place', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tool', postgresql.ARRAY(postgresql.ENUM('noSelect', 'Phone', 'computer', 'ipad', 'textbook', 'notebook', name='toolenum')), autoincrement=False, nullable=True),
    sa.Column('event_type', postgresql.ENUM('INPROGRESS', 'PAUSE_START', 'PAUSE_END', 'QUIT', 'COMPLETE', name='event_type'), autoincrement=False, nullable=False),
    sa.Column('duration_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('records_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('records_pkey'))
    )
    op.create_index(op.f('ix_records_user_id'), 'records', ['user_id'], unique=False)
    op.create_index(op.f('ix_records_task_id'), 'records', ['task_id'], unique=False)
    op.create_index(op.f('ix_records_occurred_at'), 'records', ['occurred_at'], unique=False)
    # ### end Alembic commands ###
