"""update record table

Revision ID: dfd5caf8a380
Revises: 58e48bb2b715
Create Date: 2025-12-16 04:50:06.609252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfd5caf8a380'
down_revision: Union[str, Sequence[str], None] = '58e48bb2b715'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_records_user_id'), table_name='records')
    op.drop_constraint(op.f('records_user_id_fkey'), 'records', type_='foreignkey')
    op.drop_column('records', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('records_user_id_fkey'), 'records', 'users', ['user_id'], ['id'])
    op.create_index(op.f('ix_records_user_id'), 'records', ['user_id'], unique=False)
    # ### end Alembic commands ###
